language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - sudo apt-add-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get build-dep gstreamer1.0
 - sudo apt-get install python-scipy
 - sudo apt-get install python-gi gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
 - sudo apt-get install autoconf automake autopoint libbz2-dev libdv4-dev libfaac-dev libfaad-dev libgtk-3-dev libmjpegtools-dev libtag1-dev libasound2-dev libtool libvpx-dev libxv-dev libx11-dev libogg-dev libvorbis-dev libopencv-dev libcv-dev libhighgui-dev libv4l-dev pkg-config zlib1g-dev gtk-doc-tools yasm bison flex 

script: 
 - export PKG_CONFIG_PATH=/usr/lib/pkgconfig
 - sudo sh -c "echo /usr/local/lib > /etc/ld.so.conf.d/gstreamer-local.conf"
 - sudo ldconfig
 - git clone git://anongit.freedesktop.org/git/gstreamer/gstreamer
 - cd gstreamer
 - ./autogen.sh 
 - make
 - sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-base
 - cd gst-plugins-base
 - ./autogen.sh 
 - make
 - sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
 - cd gst-plugins-good
 - ./autogen.sh --enable-experimental
 - make
 - sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-ugly
 - cd gst-plugins-ugly
 - ./autogen.sh 
 - make
 - sudo make install
 - cd ..
 - git clone https://github.com/hyades/gst-plugins-bad
 - cd gst-plugins-bad
 - ./autogen.sh 
 - make
 - sudo make install
 - cd ..
 - git clone https://github.com/hyades/gst-switch
 - cd gst-switch
 - ./autogen 
 - make
 - sudo make install
 - cd ..
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"