compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install gstreamer1.0 gst-plugins-good1.0 gst-plugins-bad1.0 gst-plugins-ugly1.0
