language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

env:
 matrix:
  - TEST=python-api TYPE=unittest
  - TEST=python-api TYPE=integration
  - TEST=module TYPE=python
  - TEST=module TYPE=c

install:
 - ./.travis-setup.sh

script:
 - ./.travis-run.sh

after_success:
 - coveralls --exclude gio
 # - coveralls
notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"