language: c

compiler:
  - clang
  - gcc

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install .*gstreamer.*1\.0.* libgtk-3-dev

before_script:
 -  export PKG_CONFIG_PATH=$HOME"/gst/stage/lib/pkgconfig"

script: 
 - chmod +x scripts/stage
 - ./scripts/stage

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"