language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install libglib2.0-dev gir1.2-glib-2.0
 - sudo apt-get install python-gi python3-gi gstreamer1.0-tools gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-libav
 - sudo apt-get install python-scipy
 - sudo apt-get build-dep gstreamer1.0
 - sudo apt-get install autoconf automake autopoint libbz2-dev libdv4-dev libfaac-dev libfaad-dev libgtk-3-dev libmjpegtools-dev libtag1-dev libasound2-dev libtool libvpx-dev libxv-dev libx11-dev libogg-dev libvorbis-dev libopencv-dev libcv-dev libhighgui-dev libv4l-dev pkg-config zlib1g-dev gtk-doc-tools yasm bison flex
 - mkdir -p $HOME/gst/stage/lib/pkgconfig
 - export PKG_CONFIG_PATH=$HOME/gst/stage/lib/pkgconfig
 - git clone git://anongit.freedesktop.org/gstreamer/gstreamer
 - cd gstreamer
 - ./autogen.sh --prefix=$HOME/gst
 - make
 - make install
 - cd ..
 - git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-base
 - cd gst-plugins-base
 - ./autogen.sh --prefix=$HOME/gst
 - make
 - make install
 - cd ..
 - git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-base
 - cd gst-plugins-base
 - ./autogen.sh --prefix=$HOME/gst
 - make
 - make install
 - cd ..
 - git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-good
 - cd gst-plugins-good
 - ./autogen.sh --prefix=$HOME/gst --enable-experimental
 - make
 - make install
 - cd ..
 - git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-ugly
 - cd gst-plugins-ugly
 - ./autogen.sh --prefix=$HOME/gst
 - make
 - make install
 - cd ..
 - git clone https://github.com/hyades/gst-plugins-bad.git
 - cd gst-plugins-bad
 - ./autogen.sh --prefix=$HOME/gst
 - make
 - make install
 - cd ..
script: 
 - git clone https://github.com/hyades/gst-switch.git
 - cd gst-switch
 - ./autogen.sh --prefix=$HOME/gst
 - make
 - make install
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"