language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install .*gstreamer.*1\.0.* libgtk-3-dev
 - sudo apt-get install python-gi python3-gi gstreamer1.0-tools gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
 - sudo apt-get install
 - sudo apt-get install python-scipy
 - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
 - sudo apt-get build-dep gstreamer1.0
 - mkdir gst-temp
 - cd gst-temp
 - git clone git://anongit.freedesktop.org/gstreamer/gstreamer
 - cd gstreamer
 - chmod +x autogen.sh
 - ./autogen.sh && make
 - sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/gstreamer/gst-plugins-base
 - cd gst-plugins-base
 - chmod +x autogen.sh
 - ./autogen.sh && make
 - sudo make install
 - cd ../..
 - unset PKG_CONFIG_PATH


script: 
 - chmod +x scripts/stage
 - ./scripts/stage
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"