language: c

compiler:
  - clang
  - gcc

install:
  - pip install python-coveralls

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install .*gstreamer.*1\.0.* libgtk-3-dev
 - ./autogen.sh
 - py.test --cov-report html --cov gstswitch -v -s
 after_success:
 - coveralls

notifications:
  email:
    - aayushahuja@gmail.com
