language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get build-dep gstreamer1.0
 - sudo apt-get install python-scipy
 - sudo apt-get install python-gi gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0

script: 
- export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
 - git clone git://anongit.freedesktop.org/git/gstreamer/gstreamer
 - cd gstreamer
 - ./autogen.sh --prefix=/usr/local/lib
 - make
 - sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-base
 - cd gst-plugins-base
 - ./autogen.sh --prefix=/usr/local/lib
 - make
 - sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-good
 - cd gst-plugins-good
 - ./autogen.sh --prefix=/usr/local/lib
 - make
 -sudo make install
 - cd ..
 - git clone git://anongit.freedesktop.org/git/gstreamer/gst-plugins-ugly
 - cd gst-plugins-ugly
 - ./autogen.sh --prefix=/usr/local/lib
 - make
 - sudo make install
 - cd ..
 - git clone https://github.com/hyades/gst-plugins-bad
 - cd gst-plugins-bad
 - ./autogen.sh --prefix=/usr/local/lib
 - make
 - sudo make install
 - cd ..
 - git clone https://github.com/hyades/gst-switch
 - cd gst-switch
 - ./autogen --prefix=/usr/local/lib
 - make
 - sudo make install
 - cd ..
 - sudo cp $HOME/gst/stage/lib/girepository-1.0/* /usr/lib/girepository-1.0/
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"