language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install autoconf automake autopoint libbz2-dev libdv4-dev libfaac-dev libfaad-dev libgtk-3-dev libmjpegtools-dev libtag1-dev libasound2-dev libtool libtoolize libvpx-dev libxv-dev libx11-dev libogg-dev libvorbis-dev libopencv-dev libcv-dev libhighgui-dev libv4l-dev pkg-config zlib1g-dev gtk-doc-tools yasm bison flex
 - sudo apt-get build-dep gstreamer1.0
 - sudo apt-get install python-gi python3-gi gstreamer1.0-tools gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
 - sudo apt-get install python-scipy
 - mkdir -f $HOME/gst
 - cd $HOME/gst
 - 


script: 
 - chmod +x scripts/stage
 - ./scripts/stage
 - cd $HOME/gst/stage/bin/
 - ./gst-switch-srv > out.txt 2>&1
 - sleep 10
 - cat out.txt
 - exit 1
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"