language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install .*gstreamer.*1\.0.* libgtk-3-dev
 - sudo apt-get install python-gi python3-gi gstreamer1.0-tools gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
 - export PKG_CONFIG_PATH=$HOME"/gst/stage/lib/pkgconfig"
 - sudo apt-get install python-scipy

script: 
 - chmod +x scripts/stage
 - ./scripts/stage
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"