language: 
 - c
 - python

compiler:
  - gcc

python:
 - "2.7"

before_install:
 - sudo pip install -r requirements.txt --use-mirrors
 - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install .*gstreamer.*1\.0.* libgtk-3-dev
 - mkdir $HOME/gst
 - cd $HOME/gst
 - git clone https://github.com/duzy/gst-plugins-bad.git
 - cd gst-plugins-bad
 - git checkout speakertrack_new
 - cd ..
 - git clone https://github.com/hyades/gst-switch.git
 - cd gst-switch
 - git checkout python-api
 - sudo apt-get install python-gi python3-gi gstreamer1.0-tools gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
 - sudo apt-get install python-scipy
 - export PKG_CONFIG_PATH=$HOME"/gst/stage/lib/pkgconfig"


script: 
 - chmod +x scripts/stage
 - ./scripts/stage
 - cd $HOME/gst/stage/bin/
 - ./gst-switch-srv > out.txt
 - sleep 10
 - cat out.txt
 - exit 1
 - cd python-api
 - make test

after_success:
 - coveralls

notifications:
  email:
    - gst-switch-spam@googlegroups.com
  irc: "irc.freenode.org#gst-switch"